// Central, client-safe API contract catalog for the developer API panel.
//
// IMPORTANT: this file documents the requests already present in the project.
// It is intentionally NOT used to reroute production storefront traffic, so
// adding/removing the panel cannot change existing application behaviour.

export const API_CATALOG_VERSION = 1;

export const API_ENDPOINTS = [
  {
    id: "home",
    layer: "laravel-api",
    status: "active",
    group: "Storefront content",
    method: "GET",
    path: "/home",
    transport: "Next server → Laravel",
    safeProbe: true,
    cache: "ISR 600s; tags: home, site-header",
    usedBy: ["src/lib/home-data.js", "src/app/page.jsx", "SiteHeader"],
    request: "No body. Accept: application/json.",
    response: "meta, site, hero_slides[], galleries[], categories[], sections[].products[], video_sections[], footer_content",
    notes: "Primary homepage payload and shared header/menu source. hero_slides[] drives the animated product hero; galleries[] remains the fallback banner hero.",
  },
  {
    id: "hero-slides",
    layer: "laravel-api",
    status: "active",
    group: "Storefront content",
    method: "GET",
    path: "/hero-slides",
    transport: "Developer/direct read; homepage uses /home.hero_slides to avoid an extra request",
    safeProbe: true,
    cache: "No dedicated frontend fetch; /home copy inherits home ISR 600s",
    usedBy: ["src/components/frontend/CapHero.jsx", "src/lib/home-data.js"],
    request: "No body. Accept: application/json.",
    response: "{ data: [{ id, sort_order, image, name, model, sku, price, price_formatted, product_id, product_slug, url }] }",
    notes: "Exact API projection of Laravel hero_slides + active product data, ordered by sort_order then id, maximum 10.",
  },
  {
    id: "footer",
    layer: "laravel-api",
    status: "active",
    group: "Storefront content",
    method: "GET",
    path: "/footer",
    transport: "Next server/direct + /api/footer proxy",
    safeProbe: true,
    cache: "Server helper ISR 3600s; browser proxy no-store",
    usedBy: ["src/lib/footer-data.js", "src/app/api/footer/route.js", "Footer", "Contact Us"],
    request: "No body. Accept: application/json.",
    response: "{ success, data: { meta, widget_one[], widget_two[], showrooms[], social_links } }",
    notes: "The server helper requires success=true and data to be present.",
  },
  {
    id: "about",
    layer: "laravel-api",
    status: "active",
    group: "Storefront content",
    method: "GET",
    path: "/about",
    transport: "Browser → /api/about → Laravel",
    safeProbe: true,
    cache: "no-store",
    usedBy: ["src/app/api/about/route.js", "src/app/about-us/About.jsx"],
    request: "No body. Accept: application/json.",
    response: "data/about/root object; consumed fields include ceo_description, ceo_speech_title, about_title, about_description, about_thumbnail/image/thumbnail/ceo_image",
    notes: "Frontend tolerates several wrapper shapes through normalizeAboutResponse().",
  },
  {
    id: "shop",
    layer: "laravel-api",
    status: "active",
    group: "Catalog",
    method: "GET",
    path: "/shop",
    transport: "Initial SSR direct; subsequent browser requests through cart-proxy",
    safeProbe: true,
    cache: "Initial SSR ISR 300s; client requests no-store",
    usedBy: ["src/app/shop/page.jsx", "src/app/shop/Shopview.jsx"],
    query: ["page", "limit", "sort", "availability", "brand", "minPrice", "maxPrice", "query", "category_id"],
    exampleQuery: { page: "1", limit: "12", sort: "low" },
    request: "Query-string filters only.",
    response: "products Laravel paginator (data/current_page/last_page/per_page/total), brands[], categories[]",
    notes: "Product cards consume id, name, slug/url, thumbnail/image/webp, prices, brand and current_stock.",
  },
  {
    id: "product-or-category",
    layer: "laravel-api",
    status: "active",
    group: "Catalog",
    method: "GET",
    path: "/product-or-category/{slug}",
    transport: "Next server → Laravel",
    safeProbe: true,
    cache: "ISR 300s; tags: product, category, slug:{slug}",
    usedBy: ["src/app/[slug]/page.jsx", "ProductPage", "CategoryPage"],
    pathParams: ["slug"],
    query: ["query", "q", "minPrice", "maxPrice", "brand", "brand_id", "sort", "availability", "status", "limit", "page", "filters[*]"],
    request: "Slug path parameter; category filtering/search params are forwarded unchanged.",
    response: "Either { type:'product', product, seo? }, { type:'category', category, seo? }, redirect_to, or 404.",
    notes: "This single resolver powers both product and category routes.",
  },
  {
    id: "blog-list",
    layer: "laravel-api",
    status: "active",
    group: "Blog",
    method: "GET",
    path: "/blog",
    transport: "Next server → Laravel",
    safeProbe: true,
    cache: "no-store",
    usedBy: ["src/app/blog/page.jsx", "src/app/blog/[slug]/page.jsx sidebar fallback"],
    query: ["search", "category", "page"],
    exampleQuery: { page: "1" },
    request: "Optional search/category/page query parameters.",
    response: "{ posts: paginator, categories: [] }. Post list uses id, slug, title, thumbnail_url, thumbnail_alt, category, created_at_formatted, excerpt.",
    notes: "Also called without query parameters to populate the detail-page category sidebar.",
  },
  {
    id: "blog-detail",
    layer: "laravel-api",
    status: "active",
    group: "Blog",
    method: "GET",
    path: "/blog/{slug}",
    transport: "Next server → Laravel",
    safeProbe: true,
    cache: "no-store",
    usedBy: ["src/app/blog/[slug]/page.jsx"],
    pathParams: ["slug"],
    request: "Blog slug path parameter.",
    response: "Flexible wrapper accepted. Post consumes title/slug/content|body|description, excerpt/short_description, thumbnail_url/alt, category, tags, created_at_formatted, SEO fields; optional categories/related_posts.",
    notes: "extractPost() recursively searches several wrapper shapes.",
  },
  {
    id: "cart-get",
    layer: "laravel-api",
    status: "active",
    group: "Cart & checkout",
    method: "GET",
    path: "/cart",
    transport: "Browser → /api/cart-proxy/cart → Laravel",
    safeProbe: false,
    cache: "no-store",
    session: "X-Cart-Token + guest_id cookie",
    usedBy: ["src/context/CartContext.jsx", "Cart page", "Checkout page"],
    request: "No body. Guest cart identity is forwarded by the proxy.",
    response: "{ data: { items: [], summary: { count, quantity?, subtotal } } }. Items use id, product{name,thumbnail_url|thumbnail}, price, quantity, total_price and may include shipping_type.",
    notes: "Not live-probed by the panel because it is session scoped.",
  },
  {
    id: "cart-add",
    layer: "laravel-api",
    status: "active",
    group: "Cart & checkout",
    method: "POST",
    path: "/cart/add",
    transport: "Browser → cart-proxy → Laravel",
    safeProbe: false,
    cache: "no-store",
    session: "X-Cart-Token + guest_id cookie",
    usedBy: ["src/context/CartContext.jsx", "ProductPage", "AddToCartButton"],
    body: { product_id: "number|string", quantity: "number" },
    request: "JSON: { product_id, quantity }.",
    response: "Same normalized cart envelope as GET /cart is expected.",
  },
  {
    id: "cart-update",
    layer: "laravel-api",
    status: "active",
    group: "Cart & checkout",
    method: "PATCH",
    path: "/cart/{cartId}",
    transport: "Browser → cart-proxy → Laravel",
    safeProbe: false,
    cache: "no-store",
    session: "X-Cart-Token + guest_id cookie",
    usedBy: ["src/context/CartContext.jsx", "Cart page", "Checkout page"],
    pathParams: ["cartId"],
    body: { quantity: "number" },
    request: "JSON: { quantity }.",
    response: "Same normalized cart envelope as GET /cart is expected.",
  },
  {
    id: "cart-remove",
    layer: "laravel-api",
    status: "active",
    group: "Cart & checkout",
    method: "DELETE",
    path: "/cart/{cartId}",
    transport: "Browser → cart-proxy → Laravel",
    safeProbe: false,
    cache: "no-store",
    session: "X-Cart-Token + guest_id cookie",
    usedBy: ["src/context/CartContext.jsx", "Cart page", "Checkout page"],
    pathParams: ["cartId"],
    request: "No body.",
    response: "Same normalized cart envelope as GET /cart is expected.",
  },
  {
    id: "cart-clear",
    layer: "laravel-api",
    status: "active",
    group: "Cart & checkout",
    method: "DELETE",
    path: "/cart/clear",
    transport: "Browser → cart-proxy → Laravel",
    safeProbe: false,
    cache: "no-store",
    session: "X-Cart-Token + guest_id cookie",
    usedBy: ["src/context/CartContext.jsx"],
    request: "No body.",
    response: "Same normalized cart envelope with an empty cart is expected.",
  },
  {
    id: "cart-shipping",
    layer: "laravel-api",
    status: "active",
    group: "Cart & checkout",
    method: "POST",
    path: "/cart/shipping",
    transport: "Browser → cart-proxy → Laravel",
    safeProbe: false,
    cache: "no-store",
    session: "X-Cart-Token + guest_id cookie",
    usedBy: ["src/app/checkout/CheckoutClient.jsx"],
    body: { shipping_type: "inside_dhaka | outside_dhaka" },
    request: "JSON: { shipping_type }.",
    response: "message/data.message optional; frontend refreshes GET /cart afterwards for recalculated totals.",
  },
  {
    id: "checkout",
    layer: "laravel-api",
    status: "active",
    group: "Cart & checkout",
    method: "POST",
    path: "/checkout",
    transport: "Browser → cart-proxy → Laravel",
    safeProbe: false,
    cache: "no-store",
    session: "X-Cart-Token + guest_id cookie",
    usedBy: ["src/app/checkout/CheckoutClient.jsx", "OrderSuccessClient"],
    body: {
      name: "string",
      address: "string",
      phone: "string",
      notes: "string?",
      payment_type: "cash_on_delivery",
      shipping_type: "inside_dhaka | outside_dhaka",
    },
    request: "JSON customer/order fields only. Frontend does NOT send line items; Laravel must read products from the saved guest cart.",
    response: "Flexible order wrapper. Frontend resolves order number from order_number/order_no/invoice_no/id variants and order details from order/data.",
    notes: "Order-success tolerates items/order_details/orderDetails and total/grand_total/payable_amount/amount variants.",
  },
  {
    id: "wishlist",
    layer: "laravel-api",
    status: "wired-ui-disabled",
    group: "Catalog",
    method: "POST",
    path: "/wishlist",
    transport: "Browser → cart-proxy → Laravel",
    safeProbe: false,
    cache: "no-store",
    usedBy: ["src/app/shop/Shopview.jsx"],
    body: { product_id: "number|string" },
    request: "JSON: { product_id }.",
    response: "message is displayed on success.",
    notes: "Handler exists, but the current wishlist button markup is commented out.",
  },

  // Laravel public-web feeds. These do not use /api/v1.
  ...[
    ["feed-sitemap", "/sitemap.xml", "application/xml"],
    ["feed-sitemap-products", "/sitemap-products-1.xml", "application/xml"],
    ["feed-sitemap-categories", "/sitemap-categories.xml", "application/xml"],
    ["feed-sitemap-pages", "/sitemap-pages.xml", "application/xml"],
    ["feed-sitemap-static", "/sitemap-static.xml", "application/xml"],
    ["feed-sitemap-blog", "/sitemap-blog.xml", "application/xml"],
    ["feed-robots", "/robots.txt", "text/plain"],
    ["feed-meta-catalog", "/uploads/meta/catalog.csv", "text/csv"],
  ].map(([id, path, contentType]) => ({
    id,
    layer: "laravel-web",
    status: "active",
    group: "SEO & feeds",
    method: "GET",
    path,
    transport: "Public Next route → Laravel web origin",
    safeProbe: true,
    cache: "Upstream no-store; public response may be CDN cached",
    usedBy: ["src/lib/backend-feeds.js", `Next route proxy for ${path}`],
    request: "No body.",
    response: contentType,
    notes: "Uses LARAVEL_WEB_URL / Laravel public origin, not NEXT_PUBLIC_LARAVEL_APP_URL's /api/v1 path.",
  })),

  // Next-internal endpoints are included to show the complete request graph.
  {
    id: "next-about-proxy",
    layer: "next-internal",
    status: "active",
    group: "Next internal",
    method: "GET",
    path: "/api/about",
    transport: "Browser → Next",
    safeProbe: false,
    usedBy: ["src/app/about-us/About.jsx"],
    response: "Transparent JSON proxy of Laravel GET /about.",
  },
  {
    id: "next-footer-proxy",
    layer: "next-internal",
    status: "active",
    group: "Next internal",
    method: "GET",
    path: "/api/footer",
    transport: "Browser → Next",
    safeProbe: false,
    usedBy: ["src/hooks/useFooterData.js"],
    response: "Transparent JSON proxy of Laravel GET /footer.",
  },
  {
    id: "next-cart-proxy",
    layer: "next-internal",
    status: "active",
    group: "Next internal",
    method: "ANY",
    path: "/api/cart-proxy/[...path]",
    transport: "Browser → Next → Laravel",
    safeProbe: false,
    usedBy: ["src/lib/api.js"],
    response: "Status/body/content-type/set-cookie transparently forwarded.",
    notes: "Also forwards Authorization when present and maps X-Cart-Token to the configurable guest cookie.",
  },
  {
    id: "next-revalidate",
    layer: "next-internal",
    status: "active-compatibility",
    group: "Next internal",
    method: "GET/POST",
    path: "/api/revalidate",
    transport: "Admin/Laravel webhook → Next",
    safeProbe: false,
    usedBy: ["src/app/system/clear-cache/ClearCacheClient.jsx", "CMS webhook integration"],
    response: "Compatibility/no-op response in the current no-cache implementation.",
    notes: "Requires REVALIDATE_SECRET. The panel never exposes or probes this secret endpoint.",
  },
  {
    id: "youtube-channels",
    layer: "external-unused",
    status: "dormant",
    group: "Dormant/external",
    method: "GET",
    path: "https://www.googleapis.com/youtube/v3/channels",
    transport: "Next server → YouTube Data API",
    safeProbe: false,
    usedBy: ["src/lib/youtube.js"],
    response: "YouTube channel metadata/uploads playlist.",
    notes: "No current import/call site was found in the project; retained as dormant fallback code.",
  },
  {
    id: "youtube-playlist-items",
    layer: "external-unused",
    status: "dormant",
    group: "Dormant/external",
    method: "GET",
    path: "https://www.googleapis.com/youtube/v3/playlistItems",
    transport: "Next server → YouTube Data API",
    safeProbe: false,
    usedBy: ["src/lib/youtube.js"],
    response: "YouTube upload playlist videos.",
    notes: "No current import/call site was found in the project; homepage videos come from Laravel /home.video_sections.",
  },
];

export function getApiEndpoint(id) {
  return API_ENDPOINTS.find((endpoint) => endpoint.id === id) || null;
}

export function fillEndpointPath(endpoint, values = {}) {
  if (!endpoint) return "";
  return String(endpoint.path).replace(/\{([^}]+)\}/g, (_, key) => {
    const value = values?.[key];
    return value === undefined || value === null || value === ""
      ? `{${key}}`
      : encodeURIComponent(String(value));
  });
}

export function buildLaravelRouteStub(endpoint) {
  if (!endpoint || endpoint.layer !== "laravel-api") return "";
  const verbs = {
    GET: "get",
    POST: "post",
    PATCH: "patch",
    PUT: "put",
    DELETE: "delete",
  };
  const verb = verbs[endpoint.method];
  if (!verb) return "";
  return `Route::${verb}('${endpoint.path}', [ApiController::class, 'handler']);`;
}
