export const MOCK_FEATURED_VIDEOS = [
  {
    id: "featured-1",
    title: "How to Choose the Right Smart TV for Your Home",
    youtube_id: "M7lc1UVf-VE",
    published_at: "2026-07-18",
    category: "guideline",
    category_label: "Guideline",
  },
  {
    id: "featured-2",
    title: "Ponnobd Electronics Product Showcase",
    youtube_id: "aqz-KE-bpKQ",
    published_at: "2026-07-20",
    category: "latest",
    category_label: "Latest",
  },
  {
    id: "featured-3",
    title: "Smart TV Buying Guide for Bangladesh",
    youtube_id: "ysz5S6PUM-U",
    published_at: "2026-07-22",
    category: "review",
    category_label: "Review",
  },
  {
    id: "featured-4",
    title: "Inside Ponnobd: Customer Service and Delivery",
    youtube_id: "jNQXAC9IVRw",
    published_at: "2026-07-24",
    category: "shipment",
    category_label: "Shipment",
  },
  {
    id: "featured-5",
    title: "Latest Electronics Offers and Updates",
    youtube_id: "ScMzIvxBSi4",
    published_at: "2026-07-27",
    category: "offer",
    category_label: "Offer",
  },
];

export const MOCK_MEDIA_VIDEOS = [
  {
    id: "media-1",
    title: "Latest Smart TV Collection at Ponnobd",
    youtube_id: "ScMzIvxBSi4",
    published_at: "2026-07-28",
    category: "latest",
    category_label: "Latest",
  },
  {
    id: "media-2",
    title: "Special Electronics Offer Explained",
    youtube_id: "M7lc1UVf-VE",
    published_at: "2026-07-26",
    category: "offer",
    category_label: "Offer",
  },
  {
    id: "media-3",
    title: "How Ponnobd Product Delivery Works",
    youtube_id: "aqz-KE-bpKQ",
    published_at: "2026-07-24",
    category: "shipment",
    category_label: "Shipment",
  },
  {
    id: "media-4",
    title: "Brand Collaboration and Product Launch",
    youtube_id: "ysz5S6PUM-U",
    published_at: "2026-07-21",
    category: "collaboration",
    category_label: "Collaboration",
  },
  {
    id: "media-5",
    title: "Ponnobd Customer Event Highlights",
    youtube_id: "jNQXAC9IVRw",
    published_at: "2026-07-18",
    category: "event",
    category_label: "Event",
  },
  {
    id: "media-6",
    title: "Television Setup and Care Guideline",
    youtube_id: "ScMzIvxBSi4",
    published_at: "2026-07-15",
    category: "guideline",
    category_label: "Guideline",
  },
  {
    id: "media-7",
    title: "Ponnobd Achievement and Customer Milestone",
    youtube_id: "M7lc1UVf-VE",
    published_at: "2026-07-12",
    category: "achievement",
    category_label: "Achievement",
  },
  {
    id: "media-8",
    title: "Smart TV Feature Review and Comparison",
    youtube_id: "aqz-KE-bpKQ",
    published_at: "2026-07-09",
    category: "review",
    category_label: "Review",
  },
  {
    id: "media-9",
    title: "Community Support and Social Work",
    youtube_id: "ysz5S6PUM-U",
    published_at: "2026-07-05",
    category: "social-work",
    category_label: "Social Work",
  },
];